"""Fase 1 schema inicial: pessoa conta categoria fatura lancamento override_categoria

Revision ID: 418069adc183
Revises: 
Create Date: 2026-05-28 09:56:19.540414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '418069adc183'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tipo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cor', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('categoria', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categoria_nome'), ['nome'], unique=True)

    op.create_table('pessoa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pessoa', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pessoa_nome'), ['nome'], unique=True)

    op.create_table('conta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tipo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pessoa_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pessoa_id'], ['pessoa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conta', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conta_nome'), ['nome'], unique=True)

    op.create_table('override_categoria',
    sa.Column('descricao_normalizada', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.id'], ),
    sa.PrimaryKeyConstraint('descricao_normalizada')
    )
    with op.batch_alter_table('override_categoria', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_override_categoria_categoria_id'), ['categoria_id'], unique=False)

    op.create_table('fatura',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conta_id', sa.Integer(), nullable=False),
    sa.Column('arquivo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('referencia_mes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fechamento', sa.Date(), nullable=True),
    sa.Column('vencimento', sa.Date(), nullable=True),
    sa.Column('valor_total_declarado', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('qtde_transacoes', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conta_id'], ['conta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fatura', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fatura_arquivo'), ['arquivo'], unique=True)
        batch_op.create_index(batch_op.f('ix_fatura_conta_id'), ['conta_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fatura_referencia_mes'), ['referencia_mes'], unique=False)

    op.create_table('lancamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('descricao', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tipo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('conta_id', sa.Integer(), nullable=True),
    sa.Column('pessoa_id', sa.Integer(), nullable=True),
    sa.Column('fatura_id', sa.Integer(), nullable=True),
    sa.Column('referencia_mes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('parcela_atual', sa.Integer(), nullable=True),
    sa.Column('parcela_total', sa.Integer(), nullable=True),
    sa.Column('cidade', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fonte', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('arquivo_origem', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('hash_dedupe', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('observacao', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.id'], ),
    sa.ForeignKeyConstraint(['conta_id'], ['conta.id'], ),
    sa.ForeignKeyConstraint(['fatura_id'], ['fatura.id'], ),
    sa.ForeignKeyConstraint(['pessoa_id'], ['pessoa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lancamento', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lancamento_categoria_id'), ['categoria_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lancamento_conta_id'), ['conta_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lancamento_data'), ['data'], unique=False)
        batch_op.create_index(batch_op.f('ix_lancamento_descricao'), ['descricao'], unique=False)
        batch_op.create_index(batch_op.f('ix_lancamento_fatura_id'), ['fatura_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lancamento_fonte'), ['fonte'], unique=False)
        batch_op.create_index(batch_op.f('ix_lancamento_hash_dedupe'), ['hash_dedupe'], unique=True)
        batch_op.create_index(batch_op.f('ix_lancamento_pessoa_id'), ['pessoa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lancamento_referencia_mes'), ['referencia_mes'], unique=False)
        batch_op.create_index(batch_op.f('ix_lancamento_tipo'), ['tipo'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lancamento', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lancamento_tipo'))
        batch_op.drop_index(batch_op.f('ix_lancamento_referencia_mes'))
        batch_op.drop_index(batch_op.f('ix_lancamento_pessoa_id'))
        batch_op.drop_index(batch_op.f('ix_lancamento_hash_dedupe'))
        batch_op.drop_index(batch_op.f('ix_lancamento_fonte'))
        batch_op.drop_index(batch_op.f('ix_lancamento_fatura_id'))
        batch_op.drop_index(batch_op.f('ix_lancamento_descricao'))
        batch_op.drop_index(batch_op.f('ix_lancamento_data'))
        batch_op.drop_index(batch_op.f('ix_lancamento_conta_id'))
        batch_op.drop_index(batch_op.f('ix_lancamento_categoria_id'))

    op.drop_table('lancamento')
    with op.batch_alter_table('fatura', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fatura_referencia_mes'))
        batch_op.drop_index(batch_op.f('ix_fatura_conta_id'))
        batch_op.drop_index(batch_op.f('ix_fatura_arquivo'))

    op.drop_table('fatura')
    with op.batch_alter_table('override_categoria', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_override_categoria_categoria_id'))

    op.drop_table('override_categoria')
    with op.batch_alter_table('conta', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conta_nome'))

    op.drop_table('conta')
    with op.batch_alter_table('pessoa', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pessoa_nome'))

    op.drop_table('pessoa')
    with op.batch_alter_table('categoria', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categoria_nome'))

    op.drop_table('categoria')
    # ### end Alembic commands ###
